drop database HU;
drop database CTS1;
drop database CTS2;
drop database CTS3;
drop database CTS1b;
drop database CTS4;
drop database CANWEPARSELENGTH18;
drop database CUGINI;
drop database  HYDROGRAPHY;
drop database LEN_GALLAGHER;
drop database MCGINN;
drop database SCHANZLE;
drop database SHIRLEY_HURWITZ;
drop database SULLIVAN;
drop database SULLIVAN1;
drop database TIDES;
drop database SUN;
drop database FLATER