conn / as sysdba

CREATE USER TIDES
IDENTIFIED BY TIDES
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO TIDES;
GRANT create table TO TIDES;
GRANT create view TO TIDES;





CREATE USER HU
IDENTIFIED BY HU
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO HU;
GRANT create table TO HU;
GRANT create view TO HU;




CREATE USER CUGINI
IDENTIFIED BY CUGINI
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO CUGINI;
GRANT create table TO CUGINI;
GRANT create view TO CUGINI;




CREATE USER MCGINN
IDENTIFIED BY MCGINN
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO MCGINN;
GRANT create table TO MCGINN;
GRANT create view TO MCGINN;


CREATE USER SULLIVAN1
IDENTIFIED BY SULLIVAN1
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO SULLIVAN1;
GRANT create table TO SULLIVAN1;
GRANT create view TO SULLIVAN1;





CREATE USER FLATER
IDENTIFIED BY FLATER
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO FLATER;
GRANT create table TO FLATER;
GRANT create view TO FLATER;






CREATE USER CANWEPARSELENGTH18
IDENTIFIED BY CANWEPARSELENGTH18
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO CANWEPARSELENGTH18;
GRANT create table TO CANWEPARSELENGTH18;
GRANT create view TO CANWEPARSELENGTH18;



CREATE USER SUN
IDENTIFIED BY SUN
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO SUN;
GRANT create table TO SUN;
GRANT create view TO SUN;






CREATE USER SULLIVAN
IDENTIFIED BY SULLIVAN
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO SULLIVAN;
GRANT create table TO SULLIVAN;
GRANT create view TO SULLIVAN;





CREATE USER SCHANZLE
IDENTIFIED BY SCHANZLE
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO SCHANZLE;
GRANT create table TO SCHANZLE;
GRANT create view TO SCHANZLE;







CREATE USER CTS2
IDENTIFIED BY CTS2
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO CTS2;
GRANT create table TO CTS2;
GRANT create view TO CTS2;








CREATE USER CTS1
IDENTIFIED BY CTS1
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO CTS1;
GRANT create table TO CTS1;
GRANT create view TO CTS1;






CREATE USER CTS3
IDENTIFIED BY CTS3
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO CTS3;
GRANT create table TO CTS3;
GRANT create view TO CTS3;



CREATE USER CTS4
IDENTIFIED BY CTS4
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO CTS4;
GRANT create table TO CTS4;
GRANT create view TO CTS4;





CREATE USER XOPEN1
IDENTIFIED BY XOPEN1
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO XOPEN1;
GRANT create table TO XOPEN1;
GRANT create view TO XOPEN1;




CREATE USER XOPEN2
IDENTIFIED BY XOPEN2
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO XOPEN2;
GRANT create table TO XOPEN2;
GRANT create view TO XOPEN2;





CREATE USER SHIRLEY_HURWITZ
IDENTIFIED BY SHIRLEY_HURWITZ
DEFAULT TABLESPACE t
TEMPORARY TABLESPACE temp
QUOTA 10M ON t;

GRANT create session TO SHIRLEY_HURWITZ;
GRANT create table TO SHIRLEY_HURWITZ;
GRANT create view TO SHIRLEY_HURWITZ;
