conn / as sysdba

drop user SHIRLEY_HURWITZ CASCADE;
drop user FLATER CASCADE;
drop user CUGINI CASCADE;
drop user HU CASCADE;
drop user MCGINN CASCADE;
drop user SULLIVAN1 CASCADE;
drop user CANWEPARSELENGTH18 CASCADE;
drop user SUN CASCADE;
drop user SULLIVAN CASCADE;
drop user SCHANZLE CASCADE;
drop user CTS2 CASCADE;
drop user CTS1 CASCADE;
drop user CTS4 CASCADE;
drop user CTS3 CASCADE;
drop user TIDES CASCADE;
drop user XOPEN1  CASCADE;
drop user XOPEN2 CASCADE;
