SELECT COUNT(*) FROM HU.STAFF WHERE GRADE = (SELECT 16/GRADE FROM HU.STAFF WHERE EMPNUM = 'E6');
==dml081==
SCHANZLE
--ORA-01476: 除数为 0
--negative test

SELECT COUNT(*) FROM HU.STAFF WHERE GRADE < (SELECT MAX(HOURS) FROM HU.WORKS) OR    GRADE > (SELECT MAX(NUMKEY) FROM HU.UPUPUP) OR    GRADE + 100 > (SELECT MIN(HOURS) FROM HU.WORKS);
==dml084==
SCHANZLE
--ORA-00942: 表或视图不存在
-- never create Table HU.UPUPUP ????????????????

SELECT COUNT(*) FROM TEMPS WHERE HOUR_OUT IN (SELECT HOUR_IN + INTERVAL '8' HOUR FROM TEMPS);
==dml108==
FLATER
--ORA-00942: 表或视图不存在
-- Failed to create table TEMP because of column start

SELECT COUNT(*) FROM TEMPS WHERE HOUR_OUT = ANY (SELECT HOUR_IN + INTERVAL '8' HOUR FROM TEMPS);
==dml108==
FLATER
--ORA-00942: 表或视图不存在
-- Failed to create table TEMP because of column start

SELECT COUNT(*) FROM TEMPS WHERE EXTRACT (YEAR FROM ENTERED) <> SOME (SELECT EXTRACT (YEAR FROM START) FROM TEMPS);
==dml108==
FLATER
--ORA-00936: 缺失表达式
-- Failed to create table TEMP because of column start

SELECT COUNT(*) FROM TEMPS WHERE EXTRACT (YEAR FROM START) <> ALL (SELECT EXTRACT (YEAR FROM ENTERED) FROM TEMPS);
==dml108==
FLATER
--ORA-00936: 缺失表达式
-- Failed to create table TEMP because of column start

SELECT EXTRACT (HOUR FROM AVG (DWAIT)) FROM MERCH, TURNAROUND WHERE MERCH.ITEMKEY = TURNAROUND.ITEMKEY OR TURNAROUND.ITEMKEY NOT IN (SELECT ITEMKEY FROM MERCH);
==dml112==
FLATER
--ORA-00942: 表或视图不存在
-- unsupported Time type in oracle when create table 

SELECT XX.PNUM, BUDGET, HOURS, EMPNUM FROM HU.PROJ XX LEFT JOIN HU.WORKS YY ON  XX.PNUM = YY.PNUM AND HOURS * BUDGET / 160000 > (SELECT GRADE FROM HU.STAFF WHERE YY.EMPNUM = HU.STAFF.EMPNUM) ORDER BY PNUM;
==dml148==
FLATER
--ORA-01799: 列不能外部联接到子查询
--unsupported join in 

SELECT EMPNUM, SUM (HOURS) FROM WORKS OWORKS GROUP BY EMPNUM HAVING EMPNUM IN ( SELECT WORKS.EMPNUM FROM WORKS JOIN STAFF ON WORKS.EMPNUM = STAFF.EMPNUM AND HOURS < SUM (OWORKS.HOURS) / 3 AND GRADE > 10) ORDER BY EMPNUM;
==dml158==
HU
--ORA-00904: "OWORKS"."HOURS": 标识符无效
--oworks->works,不是单组分组函数 ????????????????

SELECT EMPNUM, SUM (HOURS) FROM WORKS OWORKS GROUP BY EMPNUM HAVING EMPNUM IN ( SELECT WORKS.EMPNUM FROM WORKS JOIN STAFF ON WORKS.EMPNUM = STAFF.EMPNUM AND HOURS >= 10 + AVG (OWORKS.HOURS) AND CITY = 'Deale') ORDER BY EMPNUM;
==dml158==
HU
--ORA-00904: "OWORKS"."HOURS": 标识符无效
--????????????????????????

SELECT COUNT(*) FROM   STAFF WHERE  UNIQUE(SELECT * FROM STAFF);
==xts703==
CTS1
--ORA-00936: 缺失表达式
--????????????????

SELECT COUNT(*) FROM STAFF AS X WHERE UNIQUE (SELECT * FROM STAFF AS Y WHERE X.EMPNUM = Y.EMPNUM AND X.EMPNAME  = Y.EMPNAME AND X.GRADE    = Y.GRADE AND X.CITY     = Y.CITY);
==xts703==
CTS1
--ORA-00933: SQL 命令未正确结束

SELECT COUNT(*) FROM   STAFF WHERE  UNIQUE(SELECT GRADE FROM STAFF);
==xts703==
CTS1
--ORA-00936: 缺失表达式
--？？？？？？？？？？？？？？？？？？？？？？

SELECT EMPNUM, GRADE FROM STAFF X WHERE (UNIQUE(SELECT GRADE FROM STAFF Y WHERE X.GRADE = Y.GRADE));
==xts703==
CTS1
--ORA-00936: 缺失表达式
--？？？？？？？？？？？？？？？？？？

SELECT COUNT (*) FROM STAFF X WHERE NOT UNIQUE (SELECT GRADE FROM STAFF Y WHERE X.GRADE = Y.GRADE);
==xts703==
CTS1
--ORA-00936: 缺失表达式
--？？???????????????????????

SELECT COUNT(*) FROM   STAFFC AS X WHERE UNIQUE(SELECT CITY, MGR FROM STAFFC AS Y WHERE X.GRADE = Y.GRADE);
==xts703==
CTS1
--ORA-00933: SQL 命令未正确结束

SELECT COUNT(*) FROM   STAFFC AS X WHERE NOT UNIQUE(SELECT GRADE, CITY FROM STAFFC AS Y WHERE X.GRADE = Y.GRADE);
==xts703==
CTS1
--ORA-00933: SQL 命令未正确结束

SELECT * FROM TEST6740A NATURAL FULL JOIN TEST6740B FOR READ ONLY;
==xts732==
CTS1
--ORA-00905: 缺失关键字
--for read only

SELECT * FROM TEST6740B NATURAL FULL JOIN TEST6740A FOR READ ONLY;
==xts732==
CTS1
--ORA-00905: 缺失关键字
--for read only

SELECT * FROM (TEST6840B FULL JOIN TEST6840A AS CN1 ON TEST6840B.CH_B = CN1.CH_A) FULL JOIN TEST6840A AS CN2 ON TEST6840B.NUM_B = CN2.NUM_A ORDER BY TEST6840B.NUM_B, CN1.NUM_A;
==xts733==
CTS1
--ORA-00905: 缺失关键字
--as

SELECT * FROM (TEST6840A AS CN3 FULL OUTER JOIN TEST6840A AS CN4 ON CN3.NUM_A = CN4.NUM_A) FULL OUTER JOIN (TEST6840B AS CN5 FULL OUTER JOIN TEST6840B AS CN6 ON CN5.CH_B = CN6.CH_B) ON CN3.NUM_A = CN5.NUM_B ORDER BY CN3.NUM_A;
==xts733==
CTS1
--ORA-00907: 缺失右括号
--rm as

SELECT * FROM CTS1.STAFF1 EXCEPT SELECT * FROM CTS1.STAFF4;
==yts762==
CTS1
--ORA-00933: SQL 命令未正确结束
--??

SELECT * FROM CTS1.STAFF1 EXCEPT SELECT * FROM CTS1.STAFF4;
==yts762==
CTS1
--ORA-00933: SQL 命令未正确结束
--??

SELECT EMPNAME FROM STAFF WHERE (SELECT EMPNUM FROM WORKS WHERE PNUM = 'P4') = EMPNUM;
==yts796==
CTS1
--ORA-01427: 单行子查询返回多个行
--negative test

SELECT DISTINCT A, (SELECT D FROM TW WHERE E = X.A) FROM TV AS X, TW AS Y WHERE 1 < (SELECT COUNT (*) FROM TV, TW WHERE A = X.A AND A = E);
==yts798==
CTS1
--ORA-00933: SQL 命令未正确结束
--rm as
--SELECT DISTINCT A, (SELECT D FROM TW WHERE E = X.A) FROM TV X, TW  Y WHERE 1 < (SELECT COUNT (*) FROM TV, TW WHERE A = X.A AND A = E)
--第 1 行出现错误:
--ORA-01427: 单行子查询返回多个行

SELECT DISTINCT A, (SELECT D FROM TW WHERE E = X.A) FROM TV AS X, TW AS Y WHERE A = 1;
==yts798==
CTS1
--ORA-00933: SQL 命令未正确结束
--rm as

SELECT DISTINCT A, (SELECT D FROM TW WHERE E = X.A) FROM TV AS X, TW AS Y WHERE A = 3;
==yts798==
CTS1
--ORA-00933: SQL 命令未正确结束
--rm as

SELECT COUNT (*) FROM CTS1.TTIME3 WHERE TT2 AT TIME ZONE ((SELECT TT2 FROM TTIME3 WHERE PK = 1) - (SELECT TT2 FROM TTIME3 WHERE PK = 3)) HOUR TO MINUTE < TIME '02:00:00+10:00';
==yts809==
CTS1
--ORA-00920: 无效的关系运算符
-- at ????\表视图不存在

SELECT COUNT (*) FROM CTS1.TTIME3 WHERE TIME '16:00:00+00:00' <= TT2 AT TIME ZONE ( ((SELECT TT2 FROM TTIME3 WHERE PK = 2) - (SELECT TT2 FROM TTIME3 WHERE PK = 5)) HOUR TO MINUTE - INTERVAL '08:02' HOUR TO MINUTE);
==yts809==
CTS1
--ORA-00933: SQL 命令未正确结束
-- at ????

SELECT COUNT (*) FROM CTS1.TTIME3 WHERE TS2 AT TIME ZONE ((SELECT TS2 FROM TTIME3 WHERE PK = 5) - (SELECT TS2 FROM TTIME3 WHERE PK = 6)) HOUR TO MINUTE < TIMESTAMP '1995-02-10 23:48:00+10:06';
==yts809==
CTS1
--ORA-00920: 无效的关系运算符

SELECT COUNT (*) FROM CTS1.TTIME3 WHERE TS2 AT TIME ZONE ( ((SELECT TS2 FROM TTIME3 WHERE PK = 1) - (SELECT TS2 FROM TTIME3 WHERE PK = 6)) HOUR TO MINUTE + INTERVAL -'4500:15' HOUR TO MINUTE) >= TIMESTAMP '1995-02-10 03:12:00-10:30';
==yts809==
CTS1
--ORA-00920: 无效的关系运算符

SELECT COUNT(*) FROM TTIME3 WHERE TT2 AT TIME ZONE ((SELECT TS2 FROM TTIME3 WHERE PK = 1) - (SELECT TS2 FROM TTIME3 WHERE PK = 6)) HOUR TO MINUTE < TIME '02:00:00+10:00';
==yts809==
CTS1
--ORA-00920: 无效的关系运算符

SELECT EMPNUM, (SELECT COUNT(*) FROM HU.WORKS JOIN HU.PROJ ON HU.WORKS.PNUM = HU.PROJ.PNUM AND BUDGET > AVG (OSTAFF.GRADE) * 1000 WHERE HU.WORKS.EMPNUM = OSTAFF.EMPNUM) FROM HU.STAFF AS OSTAFF ORDER BY 2, 1;
==dml160==
FLATER
--ORA-00934: 此处不允许使用分组函数

SELECT COUNT(*) FROM TIDES.LOCATIONS A WHERE NOT UNIQUE ( SELECT * FROM TIDES.LOCATIONS WHERE DEG_LATITUDE = A.DEG_LATITUDE AND DEG_LONGITUDE = A.DEG_LONGITUDE);
==dml164==
FLATER
--ORA-00936: 缺失表达式

SELECT COUNT(*) FROM HU.WORKS A WHERE UNIQUE (SELECT EMPNUM FROM HU.STAFF B WHERE A.EMPNUM = B.EMPNUM AND GRADE = 13 AND CITY = 'Deale');
==dml164==
FLATER
--ORA-00936: 缺失表达式

SELECT * FROM CORRECT_OUTPUT EXCEPT ALL SELECT * FROM LOSSY_OUTPUT ORDER BY PORTVAL;
==dml164==
FLATER
--ORA-00933: SQL 命令未正确结束
--??

SELECT * FROM CORRECT_OUTPUT WHERE PORTVAL = 1 INTERSECT ALL SELECT * FROM LOSSY_OUTPUT WHERE PORTVAL = 1;
==dml164==
FLATER
--ORA-00928: 缺失 SELECT 关键字
--rm all

SELECT * FROM CORRECT_OUTPUT WHERE PORTVAL = 2 INTERSECT ALL SELECT * FROM LOSSY_OUTPUT WHERE PORTVAL = 2;
==dml164==
FLATER
--ORA-00928: 缺失 SELECT 关键字

SELECT * FROM CORRECT_OUTPUT WHERE PORTVAL = 3 INTERSECT ALL SELECT * FROM LOSSY_OUTPUT WHERE PORTVAL = 3;
==dml164==
FLATER
--ORA-00928: 缺失 SELECT 关键字


SELECT * FROM CORRECT_OUTPUT WHERE PORTVAL = 4 INTERSECT ALL SELECT * FROM LOSSY_OUTPUT WHERE PORTVAL = 4;
==dml164==
FLATER
--ORA-00928: 缺失 SELECT 关键字

SELECT COUNT(*) FROM HU.STAFF WHERE GRADE < (SELECT MAX(HOURS) FROM HU.WORKS) OR    GRADE > (SELECT MAX(NUMKEY) FROM HU.UPUPUP) OR    GRADE + 100 > (SELECT MIN(HOURS) FROM HU.WORKS);
==dml084==
SCHANZLE
--ORA-00942: 表或视图不存在
--UPUPUP

Total:41
